AllCops:
  TargetRubyVersion: 1.9
  Exclude:
    - 'modules/**/*'
    - 'pkg/**/*'
    - 'spec/fixtures/**/*'
    - 'vendor/**/*'

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/TrailingCommaInLiteral:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/NumericLiterals:
  Enabled: false

Style/WordArray:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Layout/IndentHeredoc:
  Enabled: false
